namespace Swolesome_vip.Models;

public class SearchConfig
{
    public List<string> SourceTypes { get; set; } = new()
    {
        "twitter.com",
        "Wattpad",
        "Deezer",
        "Zynga",
        "Collection #1",
        "myspace.com",
        "last.fm",
        "myfitnesspal.com",
        "AnimalJam",
        "dailymotion.com",
        "neopets.com",
        "blankmediagames",
        "nexusmods.com",
        "canva.com",
        "Canva",
        "armorgames.com",
        "imesh.com",
        "Rambler.ru 2016",
        "webkinz.com",
        "funimation",
        "YouNow.com 2017",
        "houzz.com",
        "ferretcheck",
        "stripchat.com",
        "XSplit.com 2013",
        "mcresolver.pw",
        "StarCloud 2024",
        "CosmicPVP_IPs",
        "mpgh.net",
        "dailyquiz.me",
        "trello.com",
        "Quidd.co 2019",
        "gpotato",
        "mayngames.com",
        "flashflashrevolution.com",
        "ClubPenguinRewritten",
        "MCCentral_IPs",
        "BinWeevils.com 2017",
        "500px.com 2018",
        "doxagram",
        "idcgames.com",
        "8tracks.com 2017",
        "vimeworld.com",
        "wildstar-online.com",
        "FaithfulMC_IPs_Sept_2020",
        "Unknown Minecraft Database (????)",
        "weheartit.com",
        "jefit",
        "stockx.com",
        "xat.com",
        "shotbow.net_2016",
        "Shotbow_Emails",
        "anime-planet.com",
        "battlefieldheroes.com",
        "silkroadonline.net",
        "DesiredCraft",
        "Aryion.com 2024",
        "tienda.sickcraft.es",
        "gamesbox.com",
        "chess.com",
        "ownedcore.com",
        "MineLand (30.12.2019)",
        "smogon.com",
        "nextgenupdate.com",
        "17app.co",
        "epicbot.com",
        "ProstoTrainer (14.05.2024)",
        "MasedWorld (09.05.2018)",
        "Bookmate.com 2018",
        "TigoDating.com 2023",
        "snapchat",
        "memechat.app",
        "MagicanCloud 2024",
        "MineManClub_IPs",
        "SegaCloud 2024",
        "Aternos.org 2020",
        "breached.vc",
        "r2games.com",
        "forbes.com",
        "Acne.org 2014",
        "LimitlessMC_IPs",
        "bitcointalk.org",
        "luminpdf.com",
        "forum.facepunch.com",
        "Restorecord",
        "RestoreCord (2024)",
        "AdeptMC",
        "forum.icrafts.su",
        "iCraft.su (Forum) 2015",
        "forum.warmane.com",
        "ExVagos.org 2022",
        "xbox360iso.com",
        "OGU",
        "94.23.196.174",
        "OzoneMC",
        "Excalibur-craft.ru (Partial) 2020",
        "Kixify.com 2022",
        "Bendercraft.ru",
        "Masedworld.net 2021",
        "APK.tw 2022",
        "KasperskyClub.ru 2024",
        "Lalafo.kg 2023",
        "DoxBin Users (2025)",
        "QuestCraft",
        "SimpleMinecraft.ru 2017",
        "DecentPlayBoy.com 2019",
        "blackmarketreloaded_2013",
        "craftrise",
        "ClickASnap (Users) 2022",
        "SDxF 2019",
        "CosmicPrisons_IPs",
        "CosmicPVP_Forum",
        "Abandonia 2015",
        "Gamesalad.com 2019",
        "CSDN.net 2010",
        "Opticraft.net 2018",
        "unrealengine.com",
        "warframe.com",
        "Zacks.com 2020",
        "stoneworks",
        "SilexPVP_IPs",
        "SilexPvP.net 2018",
        "BreachPVP",
        "cardmafia.cc",
        "raidforums.com",
        "forums.ufcfightclub.com",
    };

    public List<string> InputTypes { get; set; } = new()
    {
        "username", "email", "password", "domain", "ip", "name",
        "uuid", "steamid", "phone", "discordid"
    };

    public Dictionary<string, List<string>> Synonyms { get; set; } = new()
    {
        { "email", new() { "e-mail", "facebook_email", "email_address", "email", } },
        { "password", new() { "pass", "pass_plain", "crypted_password", "encrypt_pass", "hash", "hash1", "hash2", "m_password", "plain_pass", "members_pass_hash", "member_login_key", "passwd" } },
        { "domain", new() { "site", "website", "host", "adomain", "access_domain", "server" } },
        { "username", new() { "user", "login", "nick", "handle", "uname", "username2", "members_l_username", "members_l_display_name", "display_name", "member_url", "usergroupid" } },
        { "ip", new() { "ipaddress", "hostip", "second_ip", "lastip", "logged_ip", "regip", "last_modified_ip" } },
        { "name", new() { "fullname", "person", "firstname", "lastname", "first_name", "last_name", "middle_name", "name1", "name2" } },
        { "uuid", new() { "guid", "id", "userid", "user_id", "ncid", "pub_id", "uid", "id_member" } },
        { "steamid", new() { "steam", "steamid64", "steamid" } },
        { "phone", new() { "telephone", "phone", "contact_number" } },
        { "discordid", new() { "discord", "discordid64" } },
    };

    public int MaxDepth { get; set; } = 5;
    public int Timeout { get; set; } = 10; // seconds
    public int RequestDelay { get; set; } = 4000; // milliseconds
    public int DiscardThreshold { get; set; } = 50;
    public string ApiBaseUrl { get; set; } = "https://breach.vip/api/search";
    public string ProxyUrl { get; set; } = "/api/proxy";
}